In [3]:
import os
import pandas as pd
import geopandas as gpd

In [4]:
data_pkg_path = 'data/geonames/'
filename = 'US.txt'
path = os.path.join(data_pkg_path, filename)

In [5]:
column_names = [
    'geonameid', 'name', 'asciiname', 'alternatenames',
    'latitude', 'longitude', 'feature class', 'feature code',
    'country code', 'cc2', 'admin1 code', 'admin2 code',
    'admin3 code', 'admin4 code', 'population', 'elevation',
    'dem', 'timezone', 'modification date'
]

df = pd.read_csv(path, sep='\t', names=column_names)
df.info()

C:\Users\lucaf\AppData\Local\Temp\ipykernel_23960\3259660362.py:9: DtypeWarning: Columns (0: cc2, 1: admin2 code) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path, sep='\t', names=column_names)

<class 'pandas.DataFrame'>
RangeIndex: 2237861 entries, 0 to 2237860
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   geonameid          int64
 1   name               str
 2   asciiname          str
 3   alternatenames     str
 4   latitude           float64
 5   longitude          float64
 6   feature class      str
 7   feature code       str
 8   country code       str
 9   cc2                str
 10  admin1 code        str
 11  admin2 code        object
 12  admin3 code        float64
 13  admin4 code        float64
 14  population         int64
 15  elevation          float64
 16  dem                int64
 17  timezone           str
 18  modification date  str
dtypes: float64(5), int64(3), object(1), str(10)
memory usage: 499.4+ MB

In [6]:
mountains = df[df['feature class']=='T']
mountains.head()[['name', 'latitude', 'longitude', 'dem','feature class']]

                 name  latitude  longitude   dem feature class
15       Vulcan Point  52.10222  177.53889 -9999             T
16     Tropical Ridge  51.99167  177.50833   267             T
17  Thirty-Seven Hill  52.84528  173.15278   193             T
20       Square Point  52.86120  173.33679    30             T
21       Square Bluff  51.65000  178.70000 -9999             T

In [7]:
geometry = gpd.points_from_xy(mountains.longitude, mountains.latitude)
gdf = gpd.GeoDataFrame(mountains, crs='EPSG:4326', geometry=geometry)
gdf

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature class,feature code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date,geometry
15,4045410,Vulcan Point,Vulcan Point,"Volcan Point,Vulcan Point",52.10222,177.53889,T,CAPE,US,NaN,AK,16.0,NaN,NaN,0,NaN,-9999,America/Adak,2014-10-08,POINT (177.53889 52.10222)
16,4045411,Tropical Ridge,Tropical Ridge,NaN,51.99167,177.50833,T,RDGE,US,NaN,AK,16.0,NaN,NaN,0,NaN,267,America/Adak,2010-01-30,POINT (177.50833 51.99167)
17,4045412,Thirty-Seven Hill,Thirty-Seven Hill,NaN,52.84528,173.15278,T,MT,US,NaN,AK,16.0,NaN,NaN,0,NaN,193,America/Adak,2014-10-08,POINT (173.15278 52.84528)
20,4045415,Square Point,Square Point,NaN,52.86120,173.33679,T,CAPE,US,NaN,AK,16.0,NaN,NaN,0,NaN,30,America/Adak,2014-11-17,POINT (173.33679 52.8612)
21,4045416,Square Bluff,Square Bluff,NaN,51.65000,178.70000,T,CLF,US,NaN,AK,16.0,NaN,NaN,0,NaN,-9999,America/Adak,2014-10-08,POINT (178.7 51.65)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2237736,12123289,Alum Cave Bluff,Alum Cave Bluff,NaN,35.63888,-83.44603,T,CLF,US,NaN,TN,155.0,NaN,NaN,0,1510.0,1470,America/New_York,2020-02-04,POINT (-83.44603 35.63888)
2237746,12123685,Arch Rock,Arch Rock,NaN,35.63241,-83.44496,T,RK,US,NaN,TN,155.0,NaN,NaN,0,1338.0,1206,America/New_York,2020-02-05,POINT (-83.44496 35.63241)
2237763,12129575,Hole-in-the-Rock,Hole-in-the-Rock,NaN,37.25431,-110.89622,T,RDGE,US,NaN,UT,25.0,NaN,NaN,0,NaN,1219,America/Denver,2020-03-03,POINT (-110.89622 37.25431)
2237780,12148792,Fish Lake Valley,Fish Lake Valley,NaN,37.38330,-117.83330,T,VAL,US,NaN,CA,27.0,NaN,NaN,0,NaN,1627,America/Los_Angeles,2020-03-21,POINT (-117.8333 37.3833)
2237836,12156597,Kite Hill,Kite Hill,NaN,37.75837,-122.44168,T,HLL,US,NaN,CA,75.0,NaN,NaN,0,NaN,121,America/Los_Angeles,2020-04-24,POINT (-122.44168 37.75837)